/*const TEST_GAME = {
    address: '',
    area: 'area_tp',
    booking: 'http://reserve.hallway.com.tw/reserve-system.html',
    gameTime: '100',
    id: 'tGLWtMAOrW',
    introduction: '<h4><font color="#CC99FF">轟隆一聲門開了，映入眼簾的是我們沒想過的景象...</font></h4>\n<p class="text">世界終於走到了最後平行的交叉路口，一方的人相信科技的力量才是人類最後的歸依；而另一方的人，選擇仰賴這新興的另一道曙光，魔法能量。從此世界劃分成了兩大陣營，<font color="#00CCFF"><strong>機械城</strong></font> 與 <font color="#00CCFF"><strong>魔法城 </strong></font>。</p>\n<p>在機械城裡，只有在機械學校克雷格斯堡，通過最高級新世界機械學測驗的合格者，才能執行最困難的 <strong>S+級任務</strong>。</p>\n<p>如果這一次能更加團結，或許就能出去……如果這一次能更加合作，或許就不會留下遺憾……被吸入大法師安格法的七大神器之一 安格法之鏡的新一批機械城的人們，這次會迎來怎樣的結果呢？</p>',
    likes: 12,
    limit: '6-10',
    name: '鏡止鏡入',
    nameQuery: '鏡止鏡入',
    photoUrl: 'https://i.imgur.com/SbXaiGU.jpg',
    playeds: 62,
    rate: 7.888888888888889,
    status: '6_Opened',
    studioId: 'XhVWbmdrst',
    timetable: '',
    views: 166,
    vote: 18,
    website: 'http://hallway.com.tw/%E5%AF%86%E5%AE%A4%E4%B8%BB%E9%A1%8C/%E9%8F%A1%E6%AD%A2%E9%8F%A1%E5%85%A5.html',
    youtube: 'https://www.youtube.com/watch?v=wgx78njrYEw',
    isNew: false,
    studioObj:{
      address: '台北市士林區中山北路七段14巷19-1號',
      area: 'area_tp',
      facebook: 'https://www.facebook.com/XcapeTaiwan',
      id: 'nUU2aJo7dr',
      likes: 1,
      name: 'Xcape Taiwan 實境密室脫逃',
      nameQuery: 'xcape taiwan 實境密室脫逃',
      phone: '02-2872-1157',
      photoUrl: 'https://i.imgur.com/BIs046i.jpg',
      views: 61,
      website: 'https://www.xcapetaiwan.com/'
    }

    { address: '台北市民權東路二段62號2樓',
      area: 'area_tp',
      booking: 'http://goo.gl/7NHGrg',
      gameTime: '100',
      id: '0BQ4ghG4fX',
      introduction: '流亡者們為了逃離鬼島，接下奇術師派蒂的委託，潛入日耀神殿遺跡尋找永生寶石。隨著成功找到永生寶石，流傳三百年的永生之謎也被揭開，瞭解真相的流亡者們意識到必須趕緊離開，否則將會永遠被困在這裡！ 但不慎觸發的古代封印，讓整座神殿的結構完全改變，當初進來的路已消失無蹤； 流亡者們能在時間內找到另一條生路，逃出神殿嗎？\n<h3><font color="#FFCC00">Garena X Miss GAME，所有願望一次滿足！</font></h3>\n零密碼鎖！多重場景轉換！<br />遊戲風格機關陷阱與謎題的極致展現！<br />打造藝術品般精緻道具與場景！<br />縝密刻畫細膩感人的故事情節！<br />如此經典的密室大作，怎能滿足於僅僅體驗一次？<br />\n<h3><font color="#FFCC00">Garena 流亡黯道 x Miss GAME 密室逃脫 震撼來襲！</font></h3>\n<p>雙線流程、不同玩法、不同感受，<br />唯一相同的是帶給你最棒的遊戲經歷！<br />流亡黯道原廠授權同名密室暗黑華麗登場～<br />流亡者，你能改變命運嗎？</p>',
      likes: 1,
      limit: '4-8',
      name: '流亡黯道下篇：永恆之殿',
      nameQuery: '流亡黯道下篇：永恆之殿',
      photoUrl: 'https://i.imgur.com/YJqZWmo.jpg',
      playeds: 1,
      rate: 0,
      status: '8_160702',
      studioId: 'Oo8j8033Zq',
      timetable: '',
      views: 22,
      vote: 1,
      website: 'http://goo.gl/7NHGrg',
      youtube: 'http://goo.gl/GGfbrG',
      isNew: true,
      studioObj:
       { address: '台北市中山區民權東路二段67號2樓',
         area: 'area_tp',
         facebook: 'https://www.facebook.com/MissGAMEq/',
         id: 'Oo8j8033Zq',
         likes: 20,
         name: 'Miss Game 密室逃脫',
         nameQuery: 'miss game 密室逃脫',
         phone: '0986-617-820 ',
         photoUrl: 'http://i.imgur.com/N6TI0YY.jpg',
         views: 381,
         website: 'http://www.missgame.com.tw/' } }

    { address: '台北市民權東路二段62號2樓',
  area: 'area_kh',
  booking: '',
  gameTime: '60',
  id: '04sWwwWXJo',
  introduction: '<h4><font color="#FF0000">歷史上最邪惡的軍伐 - 凱撒</font></h4>\n<p>傳說陵墓中埋藏了足以買下一整塊大陸的財寶，某日一群盜墓者意外發現了凱撒的陵墓，但在裡面發現的並不是財寶....而是一段血染的未來....</p>\n<p>不幸成為活祭品而身陷地牢之中的夥伴，究竟是要冒著一起成為活祭品的風險拯救同伴，還是要忍痛丟下他自行逃離？同伴的生與死就在你們的一念之間！！</p>',
  likes: 2,
  limit: '4-6',
  name: '索魂',
  nameQuery: '索魂',
  photoUrl: 'https://i.imgur.com/DdwBDwr.jpg',
  playeds: 5,
  rate: 7.25,
  status: '6_Opened',
  studioId: '7TcvFoYRlC',
  timetable: '',
  views: 22,
  vote: 4,
  website: 'http://drhead-kh.weebly.com/3203439746.html',
  youtube: '',
  isNew: false,
  studioObj:
   { address: '高雄市鼓山區臨海二路16號3樓',
     area: 'area_kh',
     facebook: 'https://www.facebook.com/SIAOTOU2015/',
     id: '7TcvFoYRlC',
     likes: 0,
     name: 'Dr.小頭密室逃脫',
     nameQuery: 'dr.小頭密室逃脫',
     phone: '07-552-2793',
     photoUrl: 'http://i.imgur.com/LTw2R3T.png',
     views: 20,
     website: 'http://drhead-kh.weebly.com/' } }

}

const TEST_GAME =     {
  address: '台北市民權東路二段62號2樓',
  area: 'area_kh',
  booking: '',
  gameTime: '60',
  id: '04sWwwWXJo',
  introduction: '<h4><font color="#FF0000">歷史上最邪惡的軍伐 - 凱撒</font></h4>\n<p>傳說陵墓中埋藏了足以買下一整塊大陸的財寶，某日一群盜墓者意外發現了凱撒的陵墓，但在裡面發現的並不是財寶....而是一段血染的未來....</p>\n<p>不幸成為活祭品而身陷地牢之中的夥伴，究竟是要冒著一起成為活祭品的風險拯救同伴，還是要忍痛丟下他自行逃離？同伴的生與死就在你們的一念之間！！</p>',
  likes: 2,
  limit: '4-6',
  name: '索魂',
  nameQuery: '索魂',
  photoUrl: 'https://i.imgur.com/DdwBDwr.jpg',
  playeds: 5,
  rate: 7.25,
  status: '6_Opened',
  studioId: '7TcvFoYRlC',
  timetable: '',
  views: 22,
  vote: 4,
  website: 'http://drhead-kh.weebly.com/3203439746.html',
  youtube: '',
  isNew: false,
  studioObj:
   { address: '高雄市鼓山區臨海二路16號3樓',
     area: 'area_kh',
     facebook: 'https://www.facebook.com/SIAOTOU2015/',
     id: '7TcvFoYRlC',
     likes: 0,
     name: 'Dr.小頭密室逃脫',
     nameQuery: 'dr.小頭密室逃脫',
     phone: '07-552-2793',
     photoUrl: 'http://i.imgur.com/LTw2R3T.png',
     views: 20,
     website: 'http://drhead-kh.weebly.com/' } }*/
