
export const RECEIVE_USER_PLAYED_ITEM = 'RECEIVE_USER_PLAYED_ITEM';
export const RECEIVE_CREATE_USER_PLAYED_RESULT = 'RECEIVE_CREATE_USER_PLAYED_RESULT';
export const RECEIVE_REMOVE_USER_PLAYED_RESULT ='RECEIVE_REMOVE_USER_PLAYED_RESULT';
